import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PersonalData } from "@/personalData/page";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <nav className="bg-black text-white">
              <li><Link href="/experience">experience</Link></li> 
              <li><Link href="/projects">projects</Link></li> 
              <li><Link href="/knowledges">knowledges</Link></li> 
            </nav>
            {children}
        </body>
    </html>
  );
}
